"""init_v2

Revision ID: af5ed322beed
Revises: 
Create Date: 2026-05-28 02:43:59.223810
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'af5ed322beed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authorization_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('format', sa.String(length=10), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_task_id'), 'reports', ['task_id'], unique=False)
    op.create_table('scan_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('scan_type', sa.String(length=50), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='taskstatus'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vulnerabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('cve_id', sa.String(length=50), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('target', sa.String(length=512), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('remediation', sa.Text(), nullable=True),
    sa.Column('references', sa.JSON(), nullable=True),
    sa.Column('tool_source', sa.String(length=50), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerabilities_task_id'), 'vulnerabilities', ['task_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerabilities_task_id'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_table('scan_tasks')
    op.drop_index(op.f('ix_reports_task_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_table('authorization_logs')
    # ### end Alembic commands ###
